name: Official - Publish NuGet

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-2022

    steps:
    - name: Checking out Code
      uses: actions/checkout@v2
    - name: Installing .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.400
        include-prerelease: false
    - name: Restoring Packages
      run: dotnet restore
    - name: Building Project(s)
      run: dotnet build --no-restore
    - name: Build Nuget
      run: dotnet pack Shift.Core --configuration Release
    - name: Publish Nuget
      run: dotnet nuget push "Shift.Core\bin\Release/Shift.Core.1.0.0.nupkg" --api-key ${{ secrets.NUGET_PACKAGES_PAT }} --source "github"
